name: Post-Submit Tests

on:
  push:
    branches:
      - "develop"

env:
  JAVA_VERSION: 17
  FLUTTER_CHANNEL: stable

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.0
        with:
          distribution: "zulu"
          java-version: ${{ env.JAVA_VERSION }}

      # Setup flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: flutter3.0.1-${{ env.FLUTTER_CHANNEL }} # change this to force refresh cache

      - run: flutter --version

      - name: Get dependencies
        run: ci/pub_upgrade.sh

      - name: Check for formatting issues
        run: flutter format --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze --fatal-infos --fatal-warnings .

      - name: Run Tests with coverage
        run: ci/testing.sh

      - name: Build APK
        run: flutter build apk --debug
        working-directory: ./packages/smooth_app

      - name: Upload APK to GitHub artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: packages/smooth_app/build/app/outputs/flutter-apk/app-debug.apk
