name: Pre-Submit Tests

on: pull_request

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        flutter_channel: [stable, beta]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter_channel }}
          cache: true
          cache-key: flutter3.0.1-${{ matrix.flutter_channel }} # change this to force refresh cache

      - name: Print flutter version
        run: flutter --version

      - name: Get dependencies
        run: ci/pub_upgrade.sh

      - name: Check for formatting issues
        run: flutter format --set-exit-if-changed .

      - name: Analyze dart code for errors
        run: flutter analyze --fatal-infos --fatal-warnings .

      - name: Run tests with coverage
        run: ci/testing.sh

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
